apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/RSDI-UI-component.yaml
    - ./components/petstore-component.yaml
    - ./components/installation-orchestrator-component.yaml
    - ./components/rapid-data-transfer-component.yaml
    - ./components/downloader-component.yaml
    - ./components/remote-command-component.yaml
    - ./components/service-tools-ui-component.yaml
    - ./components/service-tools-orchestrator-component.yaml
    - ./components/OTEL-Agent-Collector-component.yaml
    - ./components/service-tools-fw-component.yaml
    - ./components/digital-twin-component.yaml
    - ./components/predictive-analyics-component.yaml
    - ./components/OTEL-Agent-component.yaml
