apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Philips
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Philips
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [pd]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./pd-group.yaml
    - ./serviceability-group.yaml
    - ./rsdi-group.yaml
    - ./rsg-group.yaml
    - ./servicetools-group.yaml
    - ./telemetry-group.yaml
    
