apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: PD Serviceability Team
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Serviceability
    email: backstage@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: pd
  children: [RSDI Team, Service Tools Team, RSG Team, Telemetry Team]
