apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Containerization_RSD
  # This is an extra long description
  description: Conatinerization Support for RSD
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: RSDI Team
  providesApis:
    - petstore
    - streetlights
    - hello-world
