apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: Service Tools Team
  system: Service Tools
