apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Rapid_Data_Transfer
  description: Podcast API
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: RSDI Team
  system: Remote_Service_Gateway
