apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Remote_Command_Interpreter
  description: Playback Order
  tags:
    - java
    - service
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: Remote_Service_Gateway
