apiVersion: backstage.io/v1alpha1
kind: Component
tag:

metadata:
  name: OTEL Agent
  description: Open Telemetry Collector Agent
spec:
  type: foundational
  lifecycle: production
  owner: Telemetry team
  system: Monitoring_and_Telemetry
  subcomponentOf: wayback-archive
