apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive
  description: Archive of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: Telemetry team
  system: Monitoring_and_Telemetry
  providesApis:
    - wayback-archive
