apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-artist
  description: Artist main website
spec:
  type: website
  lifecycle: production
  owner: RSDI Team
  system: Remote Service Download
  consumesApis: ['component:artist-lookup']
